# Generated by Django 5.2.17 on 2026-10-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answerattempt",
            name="is_unknown",
            field=models.BooleanField(default=False),
        ),
    ]
