# Generated by Django 5.2.17 on 2026-09-26 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sha256", models.CharField(max_length=64, unique=True)),
                ("storage_key", models.CharField(max_length=80)),
                ("mime", models.CharField(max_length=30)),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("byte_size", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("bundle_id", models.CharField(max_length=100)),
                ("checksum", models.CharField(max_length=64, unique=True)),
                ("result", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                ("subject", models.CharField(max_length=80)),
                ("label", models.CharField(max_length=100)),
                ("sort_order", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ExamPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                ("qualification_code", models.CharField(default="rikutoku1", max_length=40)),
                ("exam_year", models.PositiveIntegerField()),
                ("session_code", models.CharField(max_length=60)),
                ("session_label", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=80)),
                ("sort_key", models.CharField(max_length=40)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("qualification_code", "exam_year", "session_code", "subject"),
                        name="paper_identity",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("stable_id", models.CharField(max_length=100, unique=True)),
                ("question_number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("verified", "verified"),
                            ("withdrawn", "withdrawn"),
                        ],
                        max_length=12,
                    ),
                ),
                ("grading_version", models.PositiveIntegerField(default=1)),
                (
                    "exam_paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="questions.exampaper"
                    ),
                ),
            ],
            options={
                "ordering": [
                    "exam_paper__sort_key",
                    "exam_paper__subject",
                    "question_number",
                    "id",
                ],
            },
        ),
        migrations.CreateModel(
            name="QuestionRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("revision_number", models.PositiveIntegerField()),
                ("grading_version", models.PositiveIntegerField()),
                ("question_type", models.CharField(default="single_choice", max_length=30)),
                ("stem_blocks", models.JSONField()),
                ("choices", models.JSONField()),
                ("correct_choice_id", models.CharField(max_length=80)),
                ("explanation_blocks", models.JSONField()),
                ("metadata", models.JSONField(default=dict)),
                ("checksum", models.CharField(max_length=64)),
                ("grading_checksum", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="questions.question",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="question",
            name="current_revision",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="questions.questionrevision",
            ),
        ),
        migrations.CreateModel(
            name="RevisionAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("local_asset_id", models.CharField(max_length=80)),
                ("usage", models.CharField(max_length=12)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="questions.asset"
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="questions.questionrevision",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="question",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="questions.topic"
            ),
        ),
        migrations.AddConstraint(
            model_name="questionrevision",
            constraint=models.UniqueConstraint(
                fields=("question", "revision_number"), name="question_revision"
            ),
        ),
        migrations.AddConstraint(
            model_name="revisionasset",
            constraint=models.UniqueConstraint(
                fields=("revision", "local_asset_id", "usage"), name="revision_asset"
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                fields=("exam_paper", "question_number"), name="paper_number"
            ),
        ),
    ]
